In [35]:
import torch
import numpy as np

# device

In [69]:
print("torch.accelerator.is_available()?", torch.accelerator.is_available())
device = 'cpu'
if torch.accelerator.is_available():
    print("torch.accelerator.current_accelerator()", torch.accelerator.current_accelerator())
    device = torch.accelerator.current_accelerator().type
print("device:", device)
print(torch.cuda.is_available())
print(torch.cuda.device_count())

torch.accelerator.is_available()? False
device: cpu
False
0


# init - from python list

In [83]:
a = torch.tensor([1, 2])
b = torch.tensor([1])
c = torch.tensor(1)
d = torch.tensor([3, 4])
e = torch.tensor([3])
f = torch.tensor(3)
print(a.shape)
print(b.shape)
print(c.shape)

torch.Size([2])
torch.Size([1])
torch.Size([])


# init 2

In [85]:
a = np.array([[1, 2, 3], [4, 5, 6]])    
b = torch.from_numpy(a)       # from numpy array
c = b.numpy()                 # to numpy array
print(a)
print(b)
print(c)
print(torch.ones_like(b))
print(torch.zeros_like(b, dtype=torch.float32))

print(torch.arange(0, 10, 2))  # 1D tensor with low, high, step
print(torch.zeros(10, dtype=torch.long))

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
[[1 2 3]
 [4 5 6]]
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0, 2, 4, 6, 8])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


# int 3 - random tensor

In [ ]:
print(torch.rand(size=(2, 3)))  # random tensor of shape (2, 3) from uniform distribution b/n 0 and 1
print(torch.randn(size=(2, 3)))  # random tensor of shape (2, 3) from normal distribution
print(torch.randint(high=10, size=(2, 3)))
print(torch.randint(low=0, high=10, size=(2, 3)))  # random tensor of shape (2, 3) with integers from 0 to 9

tensor([[0.9192, 0.4216, 0.4431],
        [0.2959, 0.0485, 0.0134]])
tensor([[-1.0541,  0.0887, -0.2586],
        [-0.4564, -1.1848, -1.1518]])
tensor([[5, 1, 9],
        [3, 7, 6]])
tensor([[5, 0, 8],
        [5, 8, 8]])
tensor([0, 2, 4, 6, 8])
tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]], dtype=torch.int32)


# identity, full, etc.

In [82]:
print(torch.eye(3, dtype=torch.int32))          # identity matrix of shape (3, 3)
print(torch.full((2,3), 7, dtype=torch.int32))  # full

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]], dtype=torch.int32)
tensor([[7, 7, 7],
        [7, 7, 7]], dtype=torch.int32)


# int 3 = random tensor - reproducible

In [68]:
torch.manual_seed(42)  # set the random seed for reproducibility
torch.cuda.manual_seed(42)  # set the random seed for CUDA (if available)
print(torch.rand(size=(2, 3)))
print(torch.rand(size=(2, 3)))
print(torch.rand(2, 3))



tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])


# tensor attributes

In [23]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(a.shape)
print(a.dtype)

# CUDA
print(a.device)
print(a.is_cuda)
print('torch.accelerator.is_available():', torch.accelerator.is_available())
if torch.accelerator.is_available():
    a = tensor.to(torch.accelerator.current_accelerator())
    b = torch.tensor([[1, 2, 3], [4, 5, 6]], device='cuda')
    print(b.device)
    print(b.is_cuda)


torch.Size([2, 3])
torch.int64
cpu
False
torch.accelerator.is_available(): False


# element wise arithmetic

In [ ]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
b = torch.tensor([[1, 2, 3], [4, 5, 6]])
c = torch.tensor([[1, 2, 3]])
print(a*b)
print(a.mul(b))
print(torch.mul(a, b))
print(a+b)
print(a + 1)

tensor([[ 1,  4,  9],
        [16, 25, 36]])
tensor([[ 1,  4,  9],
        [16, 25, 36]])
tensor([[ 1,  4,  9],
        [16, 25, 36]])
tensor([[ 2,  4,  6],
        [ 8, 10, 12]])
tensor([[2, 3, 4],
        [5, 6, 7]])
tensor([[ 1,  4,  9],
        [ 4, 10, 18]])


# matrix arithmetic

In [ ]:
a = torch.tensor([[1, 2]])
b = torch.tensor([[3], [4]])
print(torch.matmul(a, b))
print(a.matmul(b))                                          # same as above
print(a @ b)                                                # same as above
print(torch.tensor([1, 2, 3]) @ torch.tensor([2, 2, 2]))    # dot product - a 1D case of matmul
# matrix arithmetic 2

tensor([[11]])
tensor([[11]])
tensor([[11]])
tensor(12)


# matrix arithmetic 2

In [ ]:
a = torch.ones(3, 4, dtype=torch.int32)
print(a)
print(a.sum(dim=0))
print(a.sum(dim=1))
print(a.sum(dim=0, keepdim=True))
print(a.sum(dim=1, keepdim=True))

# logical operators

In [135]:
a = torch.tensor([[1, 2], [3, 4]])
print(a > 2)
print(a <= 2)

tensor([[False, False],
        [ True,  True]])
tensor([[ True,  True],
        [False, False]])


# broadcasting - element wise

In [94]:
a = torch.tensor([[1, 2]])
b = torch.tensor([[5, 6], [7, 8]])
print(a * b)

tensor([[ 5, 12],
        [ 7, 16]])


# broadcasting - @
NOTE - broadcasting only happens in the batch dimensions, not across the matrix dims themselves.

In [103]:
a = torch.rand(size=(2, 2, 3))
b = torch.rand(size=(1, 3, 2))
print(a)
print(b)
print(a @ b)

tensor([[[0.4613, 0.0069, 0.0907],
         [0.5966, 0.6330, 0.6060]],

        [[0.3639, 0.9613, 0.5715],
         [0.2050, 0.4717, 0.6201]]])
tensor([[[0.6751, 0.1465],
         [0.6874, 0.2446],
         [0.0845, 0.2269]]])
tensor([[[0.3239, 0.0898],
         [0.8891, 0.3797]],

        [[0.9548, 0.4181],
         [0.5150, 0.2861]]])


# dimension (aka rank) vs shape

In [ ]:
a = torch.tensor([[1], [2], [3]])
print(a.shape)   # shape or size
print(a.size())  # same as above
print(a.ndim)    # dimension or rank
print(a.dim())   # same as above


torch.Size([3, 1])
torch.Size([3, 1])
2
2


# min, max, argmin

In [12]:
a = torch.rand(10)
print(a)
print(a.min(), "@", a.argmin())
print(a.max(), "@", a.argmax())
print(a.sum())
print(a.mean())
print(a.std())
# this will be useful when using sofmax
max_index = a.argmax()
print(a[max_index])

tensor([0.7823, 0.5193, 0.1382, 0.5651, 0.6155, 0.5722, 0.8313, 0.8386, 0.0764,
        0.4542])
tensor(0.0764) @ tensor(8)
tensor(0.8386) @ tensor(7)
tensor(5.3929)
tensor(0.5393)
tensor(0.2634)
tensor(0.8386)


# squeeze/unsqueeze

In [54]:
a = torch.tensor([[1, 2]])
b = torch.tensor([[1]])
c = torch.tensor([1])
print(a.squeeze())
print(a.squeeze().squeeze())
print(b.squeeze())
print(c.squeeze())
#print(torch.tensor([[[1]]]).unsqueeze(0))

tensor([1, 2])
tensor([1, 2])
tensor(1)
tensor(1)


# reshape

In [50]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(a)
print(a.reshape(6, 1))
print(a.reshape(1, 6))
print(a.reshape(3, 2))
print(a.reshape(1, 6, 1))
print(a.reshape(3, -1))         ## here, -1 means "infer the size of this dimension"
print("after modification")
print(a)
b = a.reshape(1, 6)
b[0] = 100
print(a)
print(b)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[[1],
         [2],
         [3],
         [4],
         [5],
         [6]]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
after modification
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[100, 100, 100],
        [100, 100, 100]])
tensor([[100, 100, 100, 100, 100, 100]])


# view
1. view always requires compatibility
2. reshape - when compatbile, it behaves like view. otherwise, it returns a copy,
   and hence modificiation of the original won't affect the copy and vice versa

In [123]:
a = torch.tensor([[1, 2], [3, 4], [5, 6]])
print(a.view(6, 1))
print(a.view(1, 6))
print(a.view(6))
print(a.view(-1))
print(a.view(2, 3))
print(a.view(3, 2))



tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


# convert to python number or list

In [59]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(a.sum().item())  # convert to python number
print(a[-1].tolist()) # convert to python list

21
[4, 5, 6]


# indexing and slicing

In [139]:
a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a[0]) # first row
print(a[-1]) # last row
print(a[:, 0])  # first column
print(a[:, -1])  # last colunn
print(a[-1, -1])  # last element
print(a[:2, :2])  # rows upto row 2 (exclusive), columns upto column 2 (exclusive)
print(a[::2, :])    # odd rows
print(a[:, ::2])    # odd columns
print(a[:, 1::2])    # even columns
print(a[:, [0,2]])  # first and third columns
print(a[[0,1], [0,1]])

tensor([1, 2, 3])
tensor([7, 8, 9])
tensor([1, 4, 7])
tensor([3, 6, 9])
tensor(9)
tensor([[1, 2],
        [4, 5]])
tensor([[1, 2, 3],
        [7, 8, 9]])
tensor([[1, 3],
        [4, 6],
        [7, 9]])
tensor([[2],
        [5],
        [8]])
tensor([[1, 3],
        [4, 6],
        [7, 9]])
tensor([1, 5])


# cat
concatenates the given sequence along an existing dimension.

In [34]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
b = torch.tensor([[7, 8, 9], [10, 11, 12]])
print(torch.cat([a, b], dim=0))  # concatenate along rows
print(torch.cat([a, b]))         # same as before - defaults to dim 0
print(torch.cat([a, b], dim=1))  # concatenate along columns

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]])


# concat
concatenates a sequence of tensors along a new dimension.

In [14]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])
c = torch.tensor([[9, 10], [11, 12]])
print(torch.stack([a, b, c], dim=0))  # stack along rows
print(torch.stack([a, b, c], dim=0).shape)
print()
print(torch.stack([a, b, c], dim=1))  # stack along columns
print(torch.stack([a, b, c], dim=1).shape)
print()
print(torch.stack([a, b, c], dim=2))  # stack along depth
print(torch.stack([a, b, c], dim=2).shape)

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])
torch.Size([3, 2, 2])

tensor([[[ 1,  2],
         [ 5,  6],
         [ 9, 10]],

        [[ 3,  4],
         [ 7,  8],
         [11, 12]]])
torch.Size([2, 3, 2])

tensor([[[ 1,  5,  9],
         [ 2,  6, 10]],

        [[ 3,  7, 11],
         [ 4,  8, 12]]])
torch.Size([2, 2, 3])


# in-place operations
NOTE: their use is discouraged, because of loss of history and hence problems with computing derivatives

In [ ]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
a.add_(1)  # in-place addition
print(a)

tensor([[2, 3, 4],
        [5, 6, 7]])


# grad

In [151]:
a = torch.tensor([[1.0, 2.0], [3.0, 4.0]], requires_grad=True)
b = a * 2
c = b + 1
d = c.sum()
print(a.grad)
d.backward()
print(a.grad)
#print(b.grad)  # NOTE: b is not a leaf node, so it doesn't have grad
print(b)
print(c)
print(d)

None
tensor([[2., 2.],
        [2., 2.]])
tensor([[2., 4.],
        [6., 8.]], grad_fn=<MulBackward0>)
tensor([[3., 5.],
        [7., 9.]], grad_fn=<AddBackward0>)
tensor(24., grad_fn=<SumBackward0>)


# sampling from a binomial distribution

In [185]:
torch.manual_seed(42)
probabilities = torch.rand((10,), requires_grad=False)
print("values:", probabilities)
probabilities = probabilities / probabilities.sum() # normalize to sum to 1
print("probabilities:", probabilities)
sample_indices = torch.multinomial(probabilities, 10, replacement=True)  # sample 10 times with replacement
print("max:", probabilities.max())
print("min:", probabilities.min())
print("sample_indices - values:", probabilities[sample_indices])  # probabilities of the sampled indices

values: tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936, 0.9408,
        0.1332])
probabilities: tensor([0.1411, 0.1463, 0.0612, 0.1534, 0.0624, 0.0961, 0.0410, 0.1269, 0.1504,
        0.0213])
max: tensor(0.1534)
min: tensor(0.0213)
sample_indices - values: tensor([0.1534, 0.1504, 0.1504, 0.1411, 0.1411, 0.1463, 0.1534, 0.1504, 0.1504,
        0.1534])
